### PR TITLE
 Remove --registry from Dockerfile

### LINKED ISSUE #5: Remove --registry from Dockerfile
According to change of https://github.com/edgexfoundry/device-sdk-go/pull/274, once updating the device-sdk-go version to v1.0.0 in go.mod, --registry has to include the registry URL.
Thus, all the Device Services should not include --registry in the command line.  It is consistent with the C Device Services.

### PR DESCRIPTION
**Pull request by weichou1229**
Should not include --registry in the command line. It is consistent with the C Device Services.

Fix #5

### CODE REVIEW

**Comment by cloudxxx8** [comment]
@dweomer should the initial pipeline be included in edinburgh branch?

**Comment by dweomer** [comment]
@cloudxxx8 wrote:

> @dweomer should the initial pipeline be included in edinburgh branch?

IMO, yes.

**Comment by dweomer** [comment]
FYI this PR seems to have duplicated #8

**Comment by dweomer** [comment]
@weichou1229 @cloudxxx8 Can we close this in favor of #10 assuming the we rebase edinburgh from master after #8 is merged? I needed to make some changes to the `Jenkinsfile` that "fix" what was on master.

**Comment by weichou1229** [comment]
No problem.

**Pull request closed without merging**
